[package]
name = "learning-actix-web"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
actix-service = "2.0.2"
serde_json = "1.0.117"
serde = { version = "1.0.201", features = ["derive"] }
futures = "0.3.30"
